# Generated by Django 5.2 on 2025-04-24 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_migrate_genre_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='genre_fk',
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.genre'),
        ),
    ]
